### PR TITLE
Include new PostCSS plugin

### PR DESCRIPTION
**Pull request by FoundrySH**

### CODE REVIEW

**Comment by Ffloriel** [comment]
I'm closing this PR for now. I'll open it when the plugin is fully ready.

**Comment by FoundrySH** [comment]
🤔 No problem with forking an open source repo, but why wipe the commit history?

**Comment by Ffloriel** [comment]
Mistake on my end. I started by forking it but couldn't figure out how to
transfer it as a repo.
Would you be interested in maintaining the repository? I will also add you
as a npm owner so you can release new versions.

I can also fork it again if you want. Leaving it as a fork this time.

**Comment by FoundrySH** [comment]
No big deal. Want the canonical package name on npmjs.org? https://www.npmjs.com/package/postcss-purgecss

I added you on there, but not sure if you have perms to transfer the name (don't actually know how to do that myself)

**Comment by FoundrySH** [comment]
I think I can submit a support request to do that, would you want it transferred to ~fullhuman or ~ffloriel?

**Comment by Ffloriel** [comment]
thanks, ~fullhuman would be best.
I sent you an invitation so you can have admin access to the repository.

**Comment by FoundrySH** [comment]
I messaged npm to transfer the package, but it looks like you might have missed the thread. Is ff********ev@gmail.com a good email address?

**Comment by Ffloriel** [comment]
Hey @FoundrySH, thanks for letting me know. The address is correct, I missed the thread indeed.

**Pull request closed without merging**
